### ISSUE TITLE
Execptions from dead celluloid actors aren't caught

### ISSUE THREAD

**Issue by ahpook** [vagrant-landrush/landrush#107]
I'm not sure what causes this, but my landrush server frequently gets into a state where one of the 'actors' that the celluloid library croaks, the exception isn't caught by landrush, and the server no longer responds to queries. A quick `vagrant landrush restart` gets everything working again, so it's not a dealbreaker. The backtrace from `~/.vagrant.d/data/landrush/log/Landrush-Server.log` looks like:

```
E, [2015-04-23T15:35:30.554367 #1449] ERROR -- : <47376> Exception thrown while processing google.com Resolv::DNS::Resource::IN::A!
E, [2015-04-23T15:35:30.554594 #1449] ERROR -- : Celluloid::DeadActorError: attempted to call a dead actor
E, [2015-04-23T15:35:30.554783 #1449] ERROR -- : /opt/vagrant/embedded/gems/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:23:in `metho
d_missing'
E, [2015-04-23T15:35:30.554867 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/transaction.rb:109:in `passthrough'
E, [2015-04-23T15:35:30.554962 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/transaction.rb:83:in `passthrough!'
E, [2015-04-23T15:35:30.555054 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/server.rb:60:in `block (2 levels) i
n run'
E, [2015-04-23T15:35:30.555126 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:217:in `[]'
E, [2015-04-23T15:35:30.555195 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:217:in `call'
E, [2015-04-23T15:35:30.555278 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:327:in `block (2 levels) in process'
E, [2015-04-23T15:35:30.555383 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:325:in `catch'
E, [2015-04-23T15:35:30.555501 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:325:in `block in process'
E, [2015-04-23T15:35:30.555586 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:322:in `each'
E, [2015-04-23T15:35:30.555656 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:322:in `process'
E, [2015-04-23T15:35:30.555801 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/transaction.rb:192:in `process'
E, [2015-04-23T15:35:30.555887 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:106:in `block in process_que
ry'
E, [2015-04-23T15:35:30.555957 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:98:in `each'
E, [2015-04-23T15:35:30.556025 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:98:in `process_query'
E, [2015-04-23T15:35:30.556094 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/handler.rb:55:in `process_query'
E, [2015-04-23T15:35:30.556162 #1449] ERROR -- : /Users/eric/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/handler.rb:87:in `respond'
E, [2015-04-23T15:35:30.556249 #1449] ERROR -- : /opt/vagrant/embedded/gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
E, [2015-04-23T15:35:30.556321 #1449] ERROR -- : /opt/vagrant/embedded/gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
E, [2015-04-23T15:35:30.556391 #1449] ERROR -- : /opt/vagrant/embedded/gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
E, [2015-04-23T15:35:30.556459 #1449] ERROR -- : /opt/vagrant/embedded/gems/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
E, [2015-04-23T15:35:30.556528 #1449] ERROR -- : /opt/vagrant/embedded/gems/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
E, [2015-04-23T15:35:30.556597 #1449] ERROR -- : /opt/vagrant/embedded/gems/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
E, [2015-04-23T15:35:30.556665 #1449] ERROR -- : /opt/vagrant/embedded/gems/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initializ
e'
```

I'll debug further but wanted to drop this issue here in case anyone else has seen this problem.

**Comment by ezekg** [comment]
I'm getting the same thing, except running a `restart` doesn't fix the issue. I have to keep uninstalling and then reinstalling Landrush.

**Comment by peterfarrell** [comment]
We are seeing this error on Landrush all the time where our dns on the guest machines totally dies.

**Comment by hferentschik** [comment]
The upcoming version of Landrush (w/ Windows support) won't be using celluoid anymore. I think once the release is out, we can close this issue.

**Comment by ezekg** [comment]
That's awesome to hear. Are there going to be any major API changes coming? I use Landrush programmatically, so will need to migrate if there is. Windows support sounds amazing, have a few users that have been waiting for that!

**Comment by hferentschik** [comment]
Version 1.0.0 is released now which abandons Celluoid in order to be able to use Landrush on Windows as well. Hence this issue is really obsolete.

> Are there going to be any major API changes coming? I use Landrush programmatically, so will need to migrate if there are. 

Hmm, there are a few changes in Landrush:Server, so you might need to adjust. For example you need to explicitly the working directory now. This is a bit flaky imo, since_Server_ is currently a bunch of static methods. I am planning to make this a proper instance which one needs to instantiate - see issue #178. I think that would also suite your programmatic use case better. Apart from that there is now a _start_ and _run_ method. Depending on what you do, you might need to call one or the other. If you want Landrush to start in the background as separate process, call _start_. I think this is unchanged. If you have any issues upgrading let us know.

**Comment by ahpook** [comment]
🎉 glad to see this obsoleted 🎉
