### ISSUE TITLE
Unable to install landrush plugin

### ISSUE THREAD

**Issue by bdp99** [vagrant-landrush/landrush#130]
Hi!

I have that error trying to install Landrush

```
homer@SIMPSON:~$ vagrant plugin install landrush
Installing the 'landrush' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing hitimes (1.2.3), and Bundler cannot continue.
Make sure that `gem install hitimes -v '1.2.3'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb
checking for clock_gettime() in -lrt... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/ruby
	--with-rtlib
	--without-rtlib
/opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:519:in `try_link0'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:714:in `try_func'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:944:in `block in have_library'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:889:in `block in checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:888:in `checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:939:in `have_library'
	from extconf.rb:10:in `<main>'


Gem files will remain installed in /home/homer/.vagrant.d/gems/gems/hitimes-1.2.3 for inspection.
Results logged to /home/homer/.vagrant.d/gems/gems/hitimes-1.2.3/ext/hitimes/c/gem_make.out
```

And then, despite I try to do something like @phinze suggested here (https://github.com/mitchellh/vagrant/issues/5746#issue-79500912) I reach the same error

```
homer@SIMPSON:~$ vagrant plugin install /home/homer/Downloads/landrush-0.18.0.gem
Installing the '/home/homer/Downloads/landrush-0.18.0.gem' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:337:in `initialize': Permission denied - /home/homer/.vagrant.d/gems/gems/hitimes-1.2.3/CONTRIBUTING.md (Errno::EACCES)
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:337:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:337:in `block (2 levels) in extract_tar_gz'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package/tar_reader.rb:64:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:330:in `block in extract_tar_gz'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:409:in `block in open_tar_gz'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:406:in `wrap'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:406:in `open_tar_gz'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:329:in `extract_tar_gz'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:313:in `block (2 levels) in extract_files'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package/tar_reader.rb:64:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:310:in `block in extract_files'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:307:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:307:in `extract_files'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:727:in `extract_files'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:225:in `install'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:379:in `block in install'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `each_with_index'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:124:in `block in install_local'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:284:in `block in with_isolated_gem'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/user_interaction.rb:40:in `use_ui'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:283:in `with_isolated_gem'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:121:in `install_local'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/manager.rb:47:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

```
homer@SIMPSON:~$ sudo vagrant plugin install /home/homer/Downloads/landrush-0.18.0.gem
[sudo] password for homer: 
Installing the '/home/homer/Downloads/landrush-0.18.0.gem' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/ext/builder.rb:62:in `run': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

    /opt/vagrant/embedded/bin/ruby extconf.rb
checking for clock_gettime() in -lrt... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/ruby
	--with-rtlib
	--without-rtlib
/opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:519:in `try_link0'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:714:in `try_func'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:944:in `block in have_library'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:889:in `block in checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:888:in `checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:939:in `have_library'
	from extconf.rb:10:in `<main>'


Gem files will remain installed in /home/homer/.vagrant.d/gems/gems/hitimes-1.2.3 for inspection.
Results logged to /home/homer/.vagrant.d/gems/gems/hitimes-1.2.3/ext/hitimes/c/gem_make.out
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/ext/ext_conf_builder.rb:39:in `block in build'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/tempfile.rb:324:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/ext/ext_conf_builder.rb:19:in `build'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:689:in `block (3 levels) in build_extensions'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:688:in `chdir'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:688:in `block (2 levels) in build_extensions'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:687:in `synchronize'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:687:in `block in build_extensions'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:662:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:662:in `build_extensions'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:227:in `install'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:379:in `block in install'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `each_with_index'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:124:in `block in install_local'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:284:in `block in with_isolated_gem'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/user_interaction.rb:40:in `use_ui'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:283:in `with_isolated_gem'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:121:in `install_local'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/manager.rb:47:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

**Comment by dan1707** [comment]
Do you have installed vagrant as a package from your Linux distribution?
Then the installation of the plugin failed because regular users do not have write permissions on /opt/vagrant.
Just try "sudo vagrant plugin install landrush" and it should work without issues.

**Comment by njam** [comment]
@bdp99 it looks to me like the root cause is that "hitimes" won't install. I think in this case you should open this ticket at the hitimes ticket tracker.

But I'm wondering why we even install *hitimes*…

**Comment by hferentschik** [comment]
Hmm, I don't think this has anything to do with Landrush. As you can see in the[ Gemfile.lock](https://github.com/vagrant-landrush/landrush/blob/master/Gemfile.lock), hitimes is not even a dependency of Landrush. 

I have seen similar issues with Landrush though, where installing new plugins causes strange installation errors (or native extension compilation errors). AFAICT this happens in combination with other plugins. Do you have any other plugins installed? I'd try removing all plugins and re-installing them one by one. Potentially you maybe also want to re-install Vagrant to make sure the Ruby installation it comes with is "clean".

I don't think there is anything we can do from the Landrush side for now.
