### ISSUE TITLE
Landrush crashes with 'TypeError: no implicit conversion from nil to integer'

### ISSUE THREAD

**Issue by babilen** [vagrant-landrush/landrush#169]
Hi,

when using landrush the guest can, unfortunately, no longer resolve domain names and I see the following behaviour:

```
$ vagrant landrush status
[landrush] Daemon status: crashed
Dumping daemon crash log:
=== Daemon Exception Backtrace @ 2016-04-08 09:32:49 +0200 ===E, [2016-04-08T09:32:49.352227 #18221] ERROR -- : Actor crashed!
Celluloid::TimeoutError: linking timeout of 5 seconds exceeded
	/home/babilen/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/actor.rb:206:in `block in linking_request'
	/home/babilen/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:107:in `exclusive'
	/home/babilen/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid.rb:414:in `exclusive'
...
```

I checked `~/.vagrant.d/data/landrush/log/Landrush-Server.log` and found the following:

```
=== Log Marked @ 2016-04-08 09:45:53 +0200 ===
I, [2016-04-08T09:45:53.757376 #18902]  INFO -- : Starting RubyDNS server (v1.0.2)...
I, [2016-04-08T09:45:53.757472 #18902]  INFO -- : <> Listening on udp:0.0.0.0:10053
E, [2016-04-08T09:45:53.758059 #18902] ERROR -- : Actor crashed!
TypeError: no implicit conversion from nil to integer
	/usr/lib/ruby/2.3.0/socket.rb:1266:in `__recvfrom_nonblock'
	/usr/lib/ruby/2.3.0/socket.rb:1266:in `recvfrom_nonblock'
	/home/babilen/.vagrant.d/gems/gems/celluloid-io-0.16.2/lib/celluloid/io/udp_socket.rb:22:in `recvfrom'
	/home/babilen/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/handler.rb:115:in `handle_connection'
	/home/babilen/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/handler.rb:81:in `block in run'
	/home/babilen/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/handler.rb:81:in `loop'
	/home/babilen/.vagrant.d/gems/gems/rubydns-1.0.2/lib/rubydns/handler.rb:81:in `run'
	/home/babilen/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/home/babilen/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/home/babilen/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
	/home/babilen/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/home/babilen/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/home/babilen/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/home/babilen/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/home/babilen/.vagrant.d/gems/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```
after "vagrant landrush restart`

**Comment by njam** [comment]
Huh, maybe some incompatibility of celluloid 0.16 and ruby 2.3?

Do you have a chance to test with an older ruby version?

**Comment by babilen** [comment]
I was running vagrant as packaged by Debian and I couldn't reproduce it with the version provided by upstream. It still looks as if there are some compatibility issues with some of the versions of the libraries that are in use.

A `vagrant plugin install landrush --verbose` results in the following for Debian's and upstream's version respectively:

```
cat vagrant_upstream 
builder 3.2.2                           Using
bundler 1.10.6                          Using
celluloid 0.16.0                        Installing
celluloid-io 0.16.2                     Installing
childprocess 0.5.9                      Using

erubis 2.7.0                            Using
excon 0.49.0                            Using
ffi 1.9.10                              Using
fog-core 1.37.0                         Using
fog-json 1.0.2                          Using
fog-libvirt 0.0.3                       Using
fog-xml 0.1.2                           Using
formatador 0.2.5                        Using
gssapi 1.2.0                            Using
gyoku 1.3.1                             Using
hashicorp-checkpoint 0.1.4              Using
hitimes 1.2.3 with native extensions    Installing

httpclient 2.7.1                        Using
i18n 0.7.0                              Using
json 1.8.3                              Using
landrush 0.19.0                         Installing
listen 3.0.5                            Using
little-plugger 1.1.4                    Using
log4r 1.1.10                            Using
logging 1.8.2                           Using
mime-types 1.25.1                       Using
mini_portile 0.6.0                      Using
multi_json 1.11.2                       Using
net-scp 1.1.2                           Using
net-sftp 2.1.2                          Using
net-ssh 3.0.2                           Using
nio4r 1.2.1 with native extensions      Installing
nokogiri 1.6.3.1                        Using
nori 2.6.0                              Using
rainbow 2.1.0                           Installing
rb-fsevent 0.9.6                        Using
rb-inotify 0.9.5                        Using
rb-kqueue 0.2.4                         Using
rest-client 1.6.9                       Using
rexec 1.6.3                             Installing
ruby-libvirt 0.6.0                      Using
rubydns 1.0.2                           Installing
rubyntlm 0.4.0                          Using
rubyzip 1.1.7                           Using
timers 4.0.4                            Installing



uuidtools 2.1.5                         Using


vagrant 1.8.1                           Using
vagrant-libvirt 0.0.33                  Using
vagrant-share 1.1.5                     Using
wdm 0.1.1                               Using
winrm 1.3.6                             Using
winrm-fs 0.2.3                          Using

$ cat vagrant_debian 
builder 3.2.2                           Using
bundler 1.11.2                          Using
celluloid 0.16.0                        Installing
celluloid-io 0.16.2                     Installing
childprocess 0.5.9                      Using
domain_name 0.5.20160310                Using
erubis 2.7.0                            Using
excon 0.49.0                            Using
ffi 1.9.10                              Using
fog-core 1.37.0                         Using
fog-json 1.0.2                          Using
fog-libvirt 0.0.3                       Using
fog-xml 0.1.2                           Using
formatador 0.2.5                        Using
hitimes 1.2.3 with native extensions    Installing
http-cookie 1.0.2                       Using

i18n 0.7.0                              Using
json 1.8.3                              Using
landrush 0.19.0                         Installing
listen 3.0.3                            Using

log4r 1.1.10                            Using

mime-types 2.99.1                       Using

multi_json 1.11.2                       Using
net-scp 1.2.1                           Using
net-sftp 2.1.2                          Using
net-ssh 3.1.1                           Using
netrc 0.11.0                            Using
nio4r 1.2.1 with native extensions      Installing
nokogiri 1.6.7.2              Using
rainbow 2.1.0                           Installing

rb-inotify 0.9.7                        Using

rest-client 1.8.0                       Using
rexec 1.6.3                             Installing
ruby-libvirt 0.6.0                      Using
rubydns 1.0.2                           Installing
timers 4.0.4                            Installing

unf 0.1.4                               Using
unf_ext 0.0.7.2                         Using



vagrant 1.8.1                           Using
vagrant-libvirt 0.0.33                  Using
```
Whitespace has been left in such a way that both are easy to diff and log entries unrelated to libraries have been removed.

**Comment by hferentschik** [comment]
@babilen any chance you tried the latest Landrush version 1.0.0? It actually downgrades the used rubydns-0.8.5. This was required to get Landrush to work on Windows. As a side effect Landrush does not depend on celluloid anymore. 

The issue seems out of date, so I'd like to close it, but I'd also be interested to hear whether Landrush 1.0.0 "fixes" your issue.

**Comment by babilen** [comment]
It worked with the new version. Thank you! Please excuse the late reply.
