### ISSUE TITLE
Failed to install on OSX 10.11.5, vagrant 1.8.1

### ISSUE THREAD

**Issue by zhangcheng** [vagrant-landrush/landrush#194]
Install output:
```
Installing the 'landrush' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing eventmachine (1.0.9.1), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.0.9.1'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

Content of ~/.vagrant.d/gems/extensions/x86_64-darwin-12/2.2.0/eventmachine-1.0.9.1/gem_make.out:
```
/opt/vagrant/embedded/bin/ruby -r ./siteconf20160609-9289-uaw01l.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
/opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:535:in `block in try_link0'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:532:in `try_link0'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:637:in `try_ldflags'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:1780:in `pkg_config'
        from extconf.rb:65:in `pkg_config_wrapper'
        from extconf.rb:92:in `<main>'

extconf failed, exit code 1
```

Content of ~/.vagrant.d/gems/extensions/x86_64-darwin-12/2.2.0/eventmachine-1.0.9.1/mkmf.log:
```
"clang -o conftest -I/opt/vagrant/embedded/include/ruby-2.2.0/x86_64-darwin12.0 -I/opt/vagrant/embedded/include/ruby-2.2.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.2.0 -I.  -I/vagrant-substrate/staging/embedded/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I/vagrant-substrate/staging/embedded/include -I/vagrant-substrate/cache/ruby-2.2.3/include -fno-common -pipe conftest.c  -L/vagrant-substrate/staging/embedded/lib -L. -L/opt/vagrant/embedded/lib -L. -L/vagrant-substrate/staging/embedded/lib  -Wl,-rpath,@loader_path/../lib -Wl,-rpath,@executable_path/../lib -Wl,-rpath,/vagrant-substrate/staging/embedded/lib -fstack-protector -L/vagrant-substrate/staging/embedded/lib   -arch x86_64   -lruby.2.2.0  -lpthread -ldl -lobjc "
In file included from conftest.c:1:
In file included from /opt/vagrant/embedded/include/ruby-2.2.0/ruby.h:33:
/opt/vagrant/embedded/include/ruby-2.2.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by zhangcheng** [comment]
Found a workaround from https://github.com/devopsgroup-io/vagrant-digitalocean/issues/232
```
» export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future
» vagrant plugin install landrush
Installing the 'landrush' plugin. This can take a few minutes...
Installed the plugin 'landrush (1.0.0)'!
```

**Comment by hferentschik** [comment]
Thanks for the report and workaround :-)
