### ISSUE TITLE
Landrush 1.0.0 conflicts with Vagrant 1.8.1

### ISSUE THREAD

**Issue by LalatenduMohanty** [vagrant-landrush/landrush#195]
I upgraded to Vagrant 1.8.1 and `vagrant up` resulted in below error. I uninstalled landrush 1.8.1 to move ahead.

```{r}
/Users/lmohanty/.vagrant.d/gems/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:8:in `require': incompatible library version - /Users/lmohanty/.vagrant.d/gems/gems/eventmachine-1.0.9.1/lib/rubyeventmachine.bundle (fatal)
	from /Users/lmohanty/.vagrant.d/gems/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:8:in `<top (required)>'
	from /Users/lmohanty/.vagrant.d/gems/gems/rubydns-0.8.5/lib/rubydns/message.rb:21:in `require'
	from /Users/lmohanty/.vagrant.d/gems/gems/rubydns-0.8.5/lib/rubydns/message.rb:21:in `<top (required)>'
	from /Users/lmohanty/.vagrant.d/gems/gems/rubydns-0.8.5/lib/rubydns.rb:23:in `require_relative'
	from /Users/lmohanty/.vagrant.d/gems/gems/rubydns-0.8.5/lib/rubydns.rb:23:in `<top (required)>'
	from /Users/lmohanty/.vagrant.d/gems/gems/landrush-1.0.0/lib/landrush.rb:7:in `require'
	from /Users/lmohanty/.vagrant.d/gems/gems/landrush-1.0.0/lib/landrush.rb:7:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:291:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `<main>'
```

**Comment by hferentschik** [comment]
> I uninstalled landrush 1.8.1 to move ahead.

I guess you mean you uninstalled Vagrant? Or did you uninstall Landrush 1.0.0?

Did you try uninstalling and re-installing the plugin? Also have you tried to delete your ~/.vagrant.d directory before the Vagrant upgrade?

**Comment by njam** [comment]
I had the same, and could fix it by reinstalling all vagrant plugins.

First uninstall:
```
rm -rf ~/.vagrant.d/gems ~/.vagrant.d/plugins.json
```
Then reinstall:
```
vagrant plugin install landrush
```

**Comment by LalatenduMohanty** [comment]
> you uninstall Landrush 1.0.0?

I had uninstalled landrush 1.0.0 to move ahead

**Comment by LalatenduMohanty** [comment]
@njam Thanks. Removing the plugins and reinstalling again worked.

```
rm -rf ~/.vagrant.d/gems ~/.vagrant.d/plugins.json
```
