### ISSUE TITLE
ResolvError: DNS result has no information for phinze.com

### ISSUE THREAD

**Issue by budhrg** [vagrant-landrush/landrush#203]
Hi,

I am getting following error on running unit tests again master branch with commit message `cut v1.0.0`:
```
➜  landrush git:(master) ✗ bundle exec rake test          
Run options: --seed 13754

# Running:

.............................E..........S.

Finished in 8.034392s, 5.2275 runs/s, 7.3434 assertions/s.

  1) Error:
Landrush::Server::start/stop#test_0002_can be queried for upstream entries:
Resolv::ResolvError: DNS result has no information for phinze.com
    /home/budhram/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/resolv.rb:384:in `getaddress'
    /home/budhram/redhat/landrush/test/landrush/server_test.rb:8:in `block in query'
    /home/budhram/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/resolv.rb:303:in `open'
    /home/budhram/redhat/landrush/test/landrush/server_test.rb:7:in `query'
    /home/budhram/redhat/landrush/test/landrush/server_test.rb:35:in `block (3 levels) in <module:Landrush>'

42 runs, 59 assertions, 0 failures, 1 errors, 1 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/budhram/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib" "/home/budhram/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" ]
/home/budhram/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/home/budhram/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

What might be problem here?

**Comment by budhrg** [comment]
It seems to be issue in office network. Working at home network.

**Comment by hferentschik** [comment]
Actually this test requires a working network connection, since it makes a DNS resolve request against Google's DNS servers. That's potentially an issue if there is no connection or other network issues (firewalls, etc). Maybe the test should be disabled!? There is a TODO in the test file.
